### PR TITLE
FS2-2574: fix shared axis range

### PR DESCRIPTION
**Pull request by JustinCCYap**

### CODE REVIEW

**Review by chschan — CHANGES_REQUESTED** [review]
Maybe take out the code for setting axis range from `addSmallMultiplesSettings()` (right at the end of the function) which doesn't seem to be working any more. Also shareRangeBetweenPanels should be called inside drawResetButton

**Comment by JustinCCYap** [comment]
I've removed the code in 8f6baa74a9b10dbd2a858a05138c3ba171520881. It doesn't seem necessary to call shareRangeBetweenPanels upon clicking reset as the range isn't changed by dragging labels and clicking reset.

**Comment by chschan** [comment]
I think it would be nice to reset the bounds anyway, because its fairly easy to change the range by double clicking or zooming in. This would make it behave in the same way as the reset button without small multiples. Is it quite a difficult change?

**Review by chschan — APPROVED** [review]

**Comment by JustinCCYap** [comment]
I've fixed the double click in 4b4e1e32e9fd795eeeb229a211631f874d85e7b7. The reset button doesn't appear after zooming in, so it doesn't make sense that it should reset the range upon clicking it. It is better to get double click working properly.

**Comment by JustinCCYap** [comment]
If we want the reset button to reset the range then we'll need to make the button appear when the user zooms, not sure how difficult it is. But I think it works quite well with double click now.

**Pull request merged**
